apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coursework-storage
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard