words_to_map = {'sci-fi', 'realist', 'orchestral-sweep', 'western', 'ensemble-driven', 'blockbuster-scale', 'atmosphere-driven', 'visual', 'real-time', 'kinetic', 'culturally-resonant', 'neo-noir', 'profound', 'meditative', 'rom-com', 'tightly-plotted', 'winsome', 'None', 'promising', 'excitement', 'violence', 'single-location', 'color-saturated', 'relentless', 'visuals-rich', 'coming-of-age', 'genre-subverting', 'dreamlike-surreal', 'emotionally evocative', 'therapy', 'multi-threaded', 'imaginative', 'antihero-centric', 'secret', 'legacy', 'political-thriller', 'detective', 'antics', 'neurotic', 'minimalist', 'adventure', 'monochrome', 'social-commentary', 'distrustful', 'emotionally-intense', 'gritty-realism', 'grave', 'redemption-focused', 'nonlinear', 'tearjerker', 'local', 'biographical'}

available_words = {
"lighthearted", "melancholic", "bittersweet", "bleak", "uplifting", "tense", "satirical", 
"heartwarming", "darkly-comic", "existentialist", "thought-provoking", "mind-bending", "nostalgic", 
"subversive", "redemption", "forbidden-love", "power-corruption", "identity-crisis", "survivalist", 
"slow-burn", "breakneck", "visually-immersive", "stylized-choreography", "dreamlike", "dialogue-heavy", 
"action-packed", "star-vehicle", "character-study", "cult-favorite", "family-oriented", "lore-rich", 
"silence-utilizing", "provocative", "political", "whimsical", "gritty", "tragic", "suspenseful", 
"comedic", "intimate", "psychedelic", "dystopian", "post-apocalyptic", "sentimental", 
"multi-layered", "morally-ambiguous", "sprawling", "atmospheric", "raw", "exuberant", "adventure", "violence"
}

semantic_mapping = {
    'sci-fi': 'mind-bending',
    'realist': 'character-study',
    'orchestral-sweep': 'stylized-choreography',
    'western': 'character-study',
    'ensemble-driven': 'multi-layered',
    'blockbuster-scale': 'action-packed',
    'atmosphere-driven': 'atmospheric',
    'visual': 'visually-immersive',
    'real-time': 'suspenseful',
    'kinetic': 'action-packed',
    'culturally-resonant': 'lore-rich',
    'neo-noir': 'gritty',
    'profound': 'thought-provoking',
    'meditative': 'thought-provoking',
    'rom-com': 'comedic',
    'tightly-plotted': 'suspenseful',
    'winsome': 'heartwarming',
    'None': 'None',
    'promising': 'uplifting',
    'excitement': 'suspenseful',
    'violence': 'violence',
    'single-location': 'intimate',
    'color-saturated': 'visually-immersive',
    'relentless': 'suspenseful',
    'visuals-rich': 'visually-immersive',
    'coming-of-age': 'character-study',
    'genre-subverting': 'subversive',
    'dreamlike-surreal': 'dreamlike',
    'emotionally evocative': 'thought-provoking',
    'therapy': 'character-study',
    'multi-threaded': 'multi-layered',
    'imaginative': 'whimsical',
    'antihero-centric': 'character-study',
    'secret': 'suspenseful',
    'legacy': 'character-study',
    'political-thriller': 'political',
    'detective': 'suspenseful',
    'antics': 'comedic',
    'neurotic': 'character-study',
    'minimalist': 'intimate',
    'adventure': 'adventure',
    'monochrome': 'gritty',
    'social-commentary': 'political',
    'distrustful': 'gritty',
    'emotionally-intense': 'sentimental',
    'gritty-realism': 'gritty',
    'grave': 'tragic',
    'redemption-focused': 'redemption',
    'nonlinear': 'multi-layered',
    'tearjerker': 'sentimental',
    'local': 'character-study',
    'biographical': 'character-study'
}